[project]
name = "campus-crowd-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "librosa>=0.11.0",
    "picamzero>=1.0.1",
    "ultralytics>=8.3.101",
]
